llamacollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('llamas/', views.llamas_index, name='index'),
    path('llamas/<int:llama_id>/', views.llamas_detail, name='detail'),
    # the new route used to show a form and create a llama
    path('llamas/create/', views.LlamaCreate.as_view(), name='llamas_create'),
    path('llamas/<int:pk>/update/',  views.LlamaUpdate.as_view(), name='llamas_update'),
    path('llamas/<int:pk>/delete/', views.LlamaDelete.as_view(), name='llamas_delete'),
    path('llamas/<int:llama_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    # adding new routes for toys below
    path('llamas/<int:llama_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    # creating a toys view page (create an html and add to views.py)
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    # Creating a toys detail page using their primary key as their id
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    # Creating a create toys page 
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    # Create an update and delete page
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

class Llama(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    # Add the M:M relationship
    toys = models.ManyToManyField(Toy)

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('detail', kwargs={'llama_id': self.id})

class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
        )
    llama = models.ForeignKey(Llama, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta: 
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Llama, Toy  # Llama and Toy class 
from .forms import FeedingForm

# Create your views here.
from django.http import HttpResponse

def home(request):
    return render(request, 'base.html')

def about(request):
    return render(request, 'about.html')

def llamas_index(request):
    llamas = Llama.objects.all()
    return render(request, 'llamas/index.html', {'llamas': llamas})

def llamas_detail(request, llama_id):
    llama = Llama.objects.get(id=llama_id)
    toys_llama_doesnt_have = Toy.objects.exclude(id__in = llama.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'llamas/detail.html', {
        'llama': llama, 'feeding_form': feeding_form, 'toys': toys_llama_doesnt_have
    })

# associating a toy to a Llama
def assoc_toy(request, llama_id, toy_id):
    Llama.objects.get(id=llama_id).toys.add(toy_id)
    return redirect('detail', llama_id=llama_id)

class LlamaCreate(CreateView):
    model = Llama 
    fields = ['name', 'breed', 'description'] # or it can be listed as fields = 
    success_url = '/llamas/'

class LlamaUpdate(UpdateView):
    model = Llama
    fields = ['breed', 'description']

class LlamaDelete(DeleteView):
    model = Llama
    success_url = '/llamas/'

def add_feeding(request, llama_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.llama_id = llama_id
        new_feeding.save()
    return redirect('detail', llama_id=llama_id)

# function for toy_index (Toy list)
class ToyList(ListView):
    model = Toy

# funtcion for toy_details
class ToyDetail(DetailView):
    model = Toy

class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(DeleteView):
    model = Toy 
    success_url = '/toys/'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Llama Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Llama Collector</h1>
    <hr />
    <p>Hire the Llama Collector!</p>
    {% endblock %}
</body>
</html>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Llama Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;LlamaCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
          <li><a href="{% url 'index' %}">View All My Llamas</a></li>
          <li><a href="{% url 'llamas_create' %}">Add a Llama</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Llama Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/llamas/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Llama Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ llama.name }}</span>
        <p>Breed: {{ llama.breed }}</p>
        <p>Description: {{ llama.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'llamas_update' llama.id %}">Edit</a>
        <a href="{% url 'llamas_delete' llama.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' llama.id %}" method='post'>
        {% csrf_token %}
        {{feeding_form.as_p}}
        <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in llama.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ llama.name }}'s Toys</h3>
      {% if llama.toys.count %}
        {% for toy in llama.toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Toys :(</h5>
      {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <!-- Available toys will come after this line -->
    <div class="col s6">
      <h3>Available Toys</h3>
      {% if toys.count %}
        {% for toy in toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{%url 'assoc_toy' llama.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{cat.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>
  </div>
  </div>

  
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/llamas/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Llama List</h1>

{% for llama in llamas %}
  <div class="card">
    <a href="{% url 'detail' llama.id %}">
    <div class="card-content">
      <span class="card-title">{{ llama.name }}</span>
      <p>Breed: {{ llama.breed }}</p>
      <p>Description: {{ llama.description }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/llama_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Llama</h1>
    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' llama.id %}">Cancel</a>
    </form>
{% endblock  %}
    

main_app/templates/main_app/llama_form.html
{% extends 'base.html' %}

{% block content %}
<!-- Leaving the form action empty below makes the form post to the same url used to display it -->
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Llama</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
<!-- Leaving the form action empty below makes the form post to the same url used to display it -->
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1> Toy's List</h1>

{% for toy in toy_list %}
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ toy.name }}</span>
                <p>Color: {{ toy.color }}</p>
            </div>
        </div>
    </a>

{% endfor %}

{% endblock %}